/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.92
 * Generated at: 2024-05-22 09:09:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.decorators;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class web_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1716349354599L));
    _jspx_dependants.put("jar:file:/D:/Desktop/JAVA-WEB-JDBC-SERVLET/workspace0/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/new-jdbc-5-month-2024/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("jar:file:/D:/Desktop/JAVA-WEB-JDBC-SERVLET/workspace0/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/new-jdbc-5-month-2024/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1695983484465L));
    _jspx_dependants.put("/common/web/header.jsp", Long.valueOf(1716368987815L));
    _jspx_dependants.put("/common/web/footer.jsp", Long.valueOf(1714967125850L));
    _jspx_dependants.put("/common/web/menu.jsp", Long.valueOf(1715235305018L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1696229999233L));
    _jspx_dependants.put("jar:file:/D:/Desktop/JAVA-WEB-JDBC-SERVLET/workspace0/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/new-jdbc-5-month-2024/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdec_005fbody_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdec_005fbody_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>");
      if (_jspx_meth_dec_005ftitle_005f0(_jspx_page_context))
        return;
      out.write("</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"icon\" type=\"image/png\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\" ");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\" ");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link\r\n");
      out.write("	href=\" ");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link href=\"template/web/vendor/animate/animate.css\" rel=\"stylesheet\"\r\n");
      out.write("	type=\"text/css\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link href=\"template/web/vendor/css-hamburgers/hamburgers.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link href=\"template/web/vendor/animsition/css/animsition.min.css\"\r\n");
      out.write("	rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link href=\"template/web/css/util.min.css\" rel=\"stylesheet\"\r\n");
      out.write("	type=\"text/css\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("<link href=\"template/web/css/main.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<!--===============================================================================================-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("	<div class=\"container-menu-desktop\">\r\n");
      out.write("		<div class=\"topbar\">\r\n");
      out.write("			<div class=\"content-topbar container h-15\">\r\n");
      out.write("				<div class=\"left-topbar\">\r\n");
      out.write("					<span class=\"left-topbar-item flex-wr-s-c\">\r\n");
      out.write("						<span>\r\n");
      out.write("							Việt Nam, Vie\r\n");
      out.write("						</span>\r\n");
      out.write("\r\n");
      out.write("						<img class=\"m-b-1 m-rl-8\" src=\"template/web/images/icons/icon-night.png\" alt=\"IMG\">\r\n");
      out.write("\r\n");
      out.write("						<span>\r\n");
      out.write("							HN 38°C\r\n");
      out.write("						</span>\r\n");
      out.write("						\r\n");
      out.write("					</span>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Header Mobile -->\r\n");
      out.write("		<div class=\"wrap-header-mobile\">\r\n");
      out.write("			<!-- Logo moblie -->\r\n");
      out.write("			<div class=\"logo-mobile\">\r\n");
      out.write("				<a href=#><img src=\"template/web/images/icons/news24h-high-resolution-logo.png\" alt=\"IMG-LOGO\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Button show menu -->\r\n");
      out.write("			<div class=\"btn-show-menu-mobile hamburger hamburger--squeeze m-r--8\">\r\n");
      out.write("				<span class=\"hamburger-box\">\r\n");
      out.write("					<span class=\"hamburger-inner\"></span>\r\n");
      out.write("				</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Menu Mobile -->\r\n");
      out.write("		<div class=\"menu-mobile\">\r\n");
      out.write("			<ul class=\"topbar-mobile\">\r\n");
      out.write("				<li class=\"left-topbar\">\r\n");
      out.write("					<span class=\"left-topbar-item flex-wr-s-c\">\r\n");
      out.write("						<span>\r\n");
      out.write("							New York, NY\r\n");
      out.write("						</span>\r\n");
      out.write("\r\n");
      out.write("						<img class=\"m-b-1 m-rl-8\" src=\"template/web/images/icons/icon-night.png\" alt=\"IMG\">\r\n");
      out.write("\r\n");
      out.write("						<span>\r\n");
      out.write("							HI 58° LO 56°\r\n");
      out.write("						</span>\r\n");
      out.write("					</span>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<ul class=\"main-menu-m\">\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"#\">Home</a>\r\n");
      out.write("					\r\n");
      out.write("					<span class=\"arrow-main-menu-m\">\r\n");
      out.write("						<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("					</span>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"#\">News</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<a href=\"#\">Video</a>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<span class=\"arrow-main-menu-m\">\r\n");
      out.write("						<i class=\"fa fa-angle-right\" aria-hidden=\"true\"></i>\r\n");
      out.write("					</span>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- MENU ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-->\r\n");
      out.write("\r\n");
      out.write("		<!--  -->\r\n");
      out.write("		<div class=\"wrap-logo container\">\r\n");
      out.write("			<!-- Logo desktop -->\r\n");
      out.write("			<div class=\"logo bo-all-1\">\r\n");
      out.write("				<a href=\"#\"><img src=\"template/web/images/icons/news24h-logo.png\" alt=\"LOGO\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!--  -->\r\n");
      out.write("		<div class=\"wrap-main-nav\">\r\n");
      out.write("			<div class=\"main-nav\">\r\n");
      out.write("				<!-- Menu desktop -->\r\n");
      out.write("				<nav class=\"menu-desktop\">\r\n");
      out.write("					<a class=\"logo-stick\" href=\"#\">\r\n");
      out.write("						<img src=\"template/web/images/icons/news24h-logo.png\" alt=\"LOGO\">\r\n");
      out.write("					</a>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"main-menu\">\r\n");
      out.write("						<li class=\"main-menu-active\">\r\n");
      out.write("							<a href=\"#\">Home</a>\r\n");
      out.write("							\r\n");
      out.write("						</li>\r\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							\r\n");
      out.write("						<li class=\"mega-menu-item\">\r\n");
      out.write("							<a href=\"#\">Video</a>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"sub-mega-menu\">\r\n");
      out.write("								<div class=\"nav flex-column nav-pills\" role=\"tablist\">\r\n");
      out.write("									<a class=\"nav-link active\" data-toggle=\"pill\" href=\"#video-1\" role=\"tab\">All</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"nav flex-column nav-pills\" role=\"tablist\">\r\n");
      out.write("									<a class=\"nav-link active\" data-toggle=\"pill\" href=\"#video-1\" role=\"tab\">All</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"nav flex-column nav-pills\" role=\"tablist\">\r\n");
      out.write("									<a class=\"nav-link active\" data-toggle=\"pill\" href=\"#video-1\" role=\"tab\">All</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"nav flex-column nav-pills\" role=\"tablist\">\r\n");
      out.write("									<a class=\"nav-link active\" data-toggle=\"pill\" href=\"#video-1\" role=\"tab\">All</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"nav flex-column nav-pills\" role=\"tablist\">\r\n");
      out.write("									<a class=\"nav-link active\" data-toggle=\"pill\" href=\"#video-1\" role=\"tab\">All</a>\r\n");
      out.write("								</div>	\r\n");
      out.write("							</div>\r\n");
      out.write("						</li>\r\n");
      out.write("\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!--------------------------------------------------------------------- conntainer ----------------------------------------------------------------- -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("	<div class=\"bg0 flex-wr-sb-c p-rl-20 p-tb-8\">\r\n");
      out.write("		<div class=\"f2-s-1 p-r-30 size-w-0 m-tb-6 flex-wr-s-c\">\r\n");
      out.write("			<span class=\"text-uppercase cl2 p-r-8\">\r\n");
      out.write("				Trending Now:\r\n");
      out.write("			</span>\r\n");
      out.write("\r\n");
      out.write("			<span class=\"dis-inline-block cl6 slide100-txt pos-relative size-w-0\" data-in=\"fadeInDown\"\r\n");
      out.write("				data-out=\"fadeOutDown\">\r\n");
      out.write("				<span class=\"dis-inline-block slide100-txt-item animated visible-false\">\r\n");
      out.write("					Interest rate angst trips up US equity bull market\r\n");
      out.write("				</span>\r\n");
      out.write("\r\n");
      out.write("				<span class=\"dis-inline-block slide100-txt-item animated visible-false\">\r\n");
      out.write("					Designer fashion show kicks off Variety Week\r\n");
      out.write("				</span>\r\n");
      out.write("\r\n");
      out.write("				<span class=\"dis-inline-block slide100-txt-item animated visible-false\">\r\n");
      out.write("					Microsoft quisque at ipsum vel orci eleifend ultrices\r\n");
      out.write("				</span>\r\n");
      out.write("			</span>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"pos-relative size-a-2 bo-1-rad-22 of-hidden bocl11 m-tb-6\">\r\n");
      out.write("			<input class=\"f1-s-1 cl6 plh9 s-full p-l-25 p-r-45\" type=\"text\" name=\"search\" placeholder=\"Search\">\r\n");
      out.write("			<button class=\"flex-c-c size-a-1 ab-t-r fs-20 cl2 hov-cl10 trans-03\">\r\n");
      out.write("				<i class=\"zmdi zmdi-search\"></i>\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      if (_jspx_meth_dec_005fbody_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"bg2 p-t-40 p-b-25\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-4 p-b-20\">\r\n");
      out.write("					<div class=\"size-h-3 flex-s-c\">\r\n");
      out.write("						<a href=\"index.html\"> <img class=\"max-s-full\"\r\n");
      out.write("							src=\"template/web/images/icons/logo-02.png\" alt=\"LOGO\">\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div>\r\n");
      out.write("						<p class=\"f1-s-1 cl11 p-b-16\">Lorem ipsum dolor sit amet,\r\n");
      out.write("							consectetur adipiscing elit. Curabitur tempor magna eget elit\r\n");
      out.write("							efficitur, at accumsan sem placerat. Nulla tellus libero, mattis\r\n");
      out.write("							nec molestie at, facilisis ut turpis. Vestibulum dolor metus,\r\n");
      out.write("							tincidunt eget odio</p>\r\n");
      out.write("\r\n");
      out.write("						<p class=\"f1-s-1 cl11 p-b-16\">Any questions? Call us on (+1)\r\n");
      out.write("							96 716 6879</p>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"p-t-15\">\r\n");
      out.write("							<a href=\"#\" class=\"fs-18 cl11 hov-cl10 trans-03 m-r-8\"> <span\r\n");
      out.write("								class=\"fab fa-facebook-f\"></span>\r\n");
      out.write("							</a> <a href=\"#\" class=\"fs-18 cl11 hov-cl10 trans-03 m-r-8\"> <span\r\n");
      out.write("								class=\"fab fa-twitter\"></span>\r\n");
      out.write("							</a> <a href=\"#\" class=\"fs-18 cl11 hov-cl10 trans-03 m-r-8\"> <span\r\n");
      out.write("								class=\"fab fa-pinterest-p\"></span>\r\n");
      out.write("							</a> <a href=\"#\" class=\"fs-18 cl11 hov-cl10 trans-03 m-r-8\"> <span\r\n");
      out.write("								class=\"fab fa-vimeo-v\"></span>\r\n");
      out.write("							</a> <a href=\"#\" class=\"fs-18 cl11 hov-cl10 trans-03 m-r-8\"> <span\r\n");
      out.write("								class=\"fab fa-youtube\"></span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-4 p-b-20\">\r\n");
      out.write("					<div class=\"size-h-3 flex-s-c\">\r\n");
      out.write("						<h5 class=\"f1-m-7 cl0\">Popular Posts</h5>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"flex-wr-sb-s p-b-20\"><a href=\"#\"\r\n");
      out.write("							class=\"size-w-4 wrap-pic-w hov1 trans-03\"> <img\r\n");
      out.write("								src=\"template/web/images/popular-post-01.jpg\" alt=\"IMG\">\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"size-w-5\">\r\n");
      out.write("								<h6 class=\"p-b-5\">\r\n");
      out.write("									<a href=\"#\" class=\"f1-s-5 cl11 hov-cl10 trans-03\"> Donec\r\n");
      out.write("										metus orci, malesuada et lectus vitae </a>\r\n");
      out.write("								</h6>\r\n");
      out.write("\r\n");
      out.write("								<span class=\"f1-s-3 cl6\"> Feb 17 </span>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"flex-wr-sb-s p-b-20\"><a href=\"#\"\r\n");
      out.write("							class=\"size-w-4 wrap-pic-w hov1 trans-03\"> <img\r\n");
      out.write("								src=\"template/web/images/popular-post-02.jpg\" alt=\"IMG\">\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"size-w-5\">\r\n");
      out.write("								<h6 class=\"p-b-5\">\r\n");
      out.write("									<a href=\"#\" class=\"f1-s-5 cl11 hov-cl10 trans-03\"> Lorem\r\n");
      out.write("										ipsum dolor sit amet, consectetur </a>\r\n");
      out.write("								</h6>\r\n");
      out.write("\r\n");
      out.write("								<span class=\"f1-s-3 cl6\"> Feb 16 </span>\r\n");
      out.write("							</div></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"flex-wr-sb-s p-b-20\"><a href=\"#\"\r\n");
      out.write("							class=\"size-w-4 wrap-pic-w hov1 trans-03\"> <img\r\n");
      out.write("								src=\"template/web/images/popular-post-03.jpg\" alt=\"IMG\">\r\n");
      out.write("						</a>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"size-w-5\">\r\n");
      out.write("								<h6 class=\"p-b-5\">\r\n");
      out.write("									<a href=\"#\" class=\"f1-s-5 cl11 hov-cl10 trans-03\">\r\n");
      out.write("										Suspendisse dictum enim quis imperdiet auctor </a>\r\n");
      out.write("								</h6>\r\n");
      out.write("\r\n");
      out.write("								<span class=\"f1-s-3 cl6\"> Feb 15 </span>\r\n");
      out.write("							</div></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-sm-6 col-lg-4 p-b-20\">\r\n");
      out.write("					<div class=\"size-h-3 flex-s-c\">\r\n");
      out.write("						<h5 class=\"f1-m-7 cl0\">Category</h5>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"m-t--12\">\r\n");
      out.write("						<li class=\"how-bor1 p-rl-5 p-tb-10\"><a href=\"#\"\r\n");
      out.write("							class=\"f1-s-5 cl11 hov-cl10 trans-03 p-tb-8\"> Fashion (22) </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"how-bor1 p-rl-5 p-tb-10\"><a href=\"#\"\r\n");
      out.write("							class=\"f1-s-5 cl11 hov-cl10 trans-03 p-tb-8\"> Technology (29)\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"how-bor1 p-rl-5 p-tb-10\"><a href=\"#\"\r\n");
      out.write("							class=\"f1-s-5 cl11 hov-cl10 trans-03 p-tb-8\"> Street Style\r\n");
      out.write("								(15) </a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"how-bor1 p-rl-5 p-tb-10\"><a href=\"#\"\r\n");
      out.write("							class=\"f1-s-5 cl11 hov-cl10 trans-03 p-tb-8\"> Life Style (28)\r\n");
      out.write("						</a></li>\r\n");
      out.write("\r\n");
      out.write("						<li class=\"how-bor1 p-rl-5 p-tb-10\"><a href=\"#\"\r\n");
      out.write("							class=\"f1-s-5 cl11 hov-cl10 trans-03 p-tb-8\"> DIY & Crafts\r\n");
      out.write("								(16) </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"bg11\">\r\n");
      out.write("		<div class=\"container size-h-4 flex-c-c p-tb-15\">\r\n");
      out.write("			<span class=\"f1-s-1 cl0 txt-center\"> Copyright © 2018 <a href=\"#\" class=\"f1-s-1 cl10 hov-link1\"></a>\r\n");
      out.write("					<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					Copyright &copy;<script>\r\n");
      out.write("						document.write(new Date().getFullYear());\r\n");
      out.write("					</script>\r\n");
      out.write("					All rights reserved | This template is made with <i\r\n");
      out.write("					class=\"fa fa-heart\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("					href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a> <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"template/web/vendor/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"template/web/vendor/animsition/js/animsition.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"template/web/vendor/bootstrap/js/popper.js\"></script>\r\n");
      out.write("	<script src=\"template/web/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!--===============================================================================================-->\r\n");
      out.write("	<script src=\"template/web/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_dec_005ftitle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dec:title
    com.opensymphony.module.sitemesh.taglib.decorator.TitleTag _jspx_th_dec_005ftitle_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.TitleTag) _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.TitleTag.class);
    boolean _jspx_th_dec_005ftitle_005f0_reused = false;
    try {
      _jspx_th_dec_005ftitle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_dec_005ftitle_005f0.setParent(null);
      // /decorators/web.jsp(6,7) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_dec_005ftitle_005f0.setDefault("Trang chủ");
      int _jspx_eval_dec_005ftitle_005f0 = _jspx_th_dec_005ftitle_005f0.doStartTag();
      if (_jspx_th_dec_005ftitle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdec_005ftitle_0026_005fdefault_005fnobody.reuse(_jspx_th_dec_005ftitle_005f0);
      _jspx_th_dec_005ftitle_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_dec_005ftitle_005f0, _jsp_getInstanceManager(), _jspx_th_dec_005ftitle_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /decorators/web.jsp(10,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue(" template/web/images/icons/favicon.png");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /decorators/web.jsp(14,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue(" template/web/vendor/bootstrap/css/bootstrap.min.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /decorators/web.jsp(18,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("template/web/fonts/fontawesome-5 .0.8/css/fontawesome-all.min.css");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /decorators/web.jsp(22,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("template/web/fonts/iconic/css/material-design-iconic-font.min.css");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /common/web/header.jsp(25,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty USERMODEL}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					\r\n");
          out.write("					<span class=\"left-topbar-item\">\r\n");
          out.write("						 ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${USERMODEL.fullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("					</span>\r\n");
          out.write("					<a href='");
          if (_jspx_meth_c_005furl_005f4(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("' class=\"left-topbar-item\">\r\n");
          out.write("						Logout\r\n");
          out.write("					</a>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /common/web/header.jsp(30,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/thoat?action=logout");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /common/web/header.jsp(35,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty USERMODEL}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					\r\n");
          out.write("					<a href='");
          if (_jspx_meth_c_005furl_005f5(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("' class=\"left-topbar-item\">\r\n");
          out.write("						Login\r\n");
          out.write("					</a>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /common/web/header.jsp(37,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/dang-nhap?action=login");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /common/web/header.jsp(129,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /common/web/header.jsp(129,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/common/web/header.jsp(129,7) '${categoties}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categoties}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<li class=\"mega-menu-item\">			\r\n");
            out.write("							<a class=\"nav-link\" data-toggle=\"pill\" href=\"#\" role=\"tab\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("							<div class=\"sub-mega-menu\">\r\n");
            out.write("								<div class=\"nav flex-column nav-pills\" role=\"tablist\">\r\n");
            out.write("									<a class=\"nav-link active\" data-toggle=\"pill\" href=\"#video-1\" role=\"tab\">All</a>\r\n");
            out.write("								</div>\r\n");
            out.write("								<div class=\"nav flex-column nav-pills\" role=\"tablist\">\r\n");
            out.write("									<a class=\"nav-link active\" data-toggle=\"pill\" href=\"#video-1\" role=\"tab\">All</a>\r\n");
            out.write("								</div>\r\n");
            out.write("								<div class=\"nav flex-column nav-pills\" role=\"tablist\">\r\n");
            out.write("									<a class=\"nav-link active\" data-toggle=\"pill\" href=\"#video-1\" role=\"tab\">All</a>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("							</li>\r\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_dec_005fbody_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  dec:body
    com.opensymphony.module.sitemesh.taglib.decorator.BodyTag _jspx_th_dec_005fbody_005f0 = (com.opensymphony.module.sitemesh.taglib.decorator.BodyTag) _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.get(com.opensymphony.module.sitemesh.taglib.decorator.BodyTag.class);
    boolean _jspx_th_dec_005fbody_005f0_reused = false;
    try {
      _jspx_th_dec_005fbody_005f0.setPageContext(_jspx_page_context);
      _jspx_th_dec_005fbody_005f0.setParent(null);
      int _jspx_eval_dec_005fbody_005f0 = _jspx_th_dec_005fbody_005f0.doStartTag();
      if (_jspx_th_dec_005fbody_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fdec_005fbody_005fnobody.reuse(_jspx_th_dec_005fbody_005f0);
      _jspx_th_dec_005fbody_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_dec_005fbody_005f0, _jsp_getInstanceManager(), _jspx_th_dec_005fbody_005f0_reused);
    }
    return false;
  }
}
